---
name: Quality Assurance
on:
    push: ~
    pull_request: ~

jobs:
    build:
        name: Build and test on ${{ matrix.go }}
        runs-on: ubuntu-latest
        strategy:
            matrix:
                go: [ '1.11', '1.12', '1.13', '1.14', '1.15' ]
        steps:
            - uses: actions/checkout@v2
            - uses: actions/setup-go@v2
              with:
                  python-version: ${{ matrix.go }}
            - run: go get -v ./...
            - run: go test -v ./...
